name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build
  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - name: Install npm dependencies
        run: npm ci      
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 211ff375f223976be2b176db61fa2bc5888bd613213b15dcb5793674921f2d66
        with:
          coverageCommand: npm run coverage
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
